---
- name : create Windows Active Directory
  hosts: localhost
  vars: 
    ansible_ssh_user: administrateur
    ansible_ssh_pass: "Boooboo0209*"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks: 
  - name: install AD services feature
    win_feature: 
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: result

  - name: create new forest
    win_domain: 
      dns_domain_name: ajcproject.local
      safe_mode_password: "Booboo0209*" 
    register: result

  - name: reboot after creation
    win_reboot: 
      msg: "Rebooting..."
    when: result.reboot_required

  - name: configure DNS
    win_dns_client: 
      adapter_names: "Ethernet 2"
      ipv4_adresses: 
      - 172.16.1.7 

  - name: promote to member
    win_domain_membership: 
      dns_domain_name: ajcproject.local 
      domain_admin_user: nadia@ajcproject.local
      domain_admin_password: "Nadia0209*"
      state: domain
    register: domain_state

  - name: reboot after joining
    win_reboot: 
      msg: "Rebooting after joining..."
    when: domain_state.reboot_required

