---
- hosts: gitjenserver
  become: yes
  tasks:
    - name: Copy docker compose file
      copy: src=docker-compose.yml dest=/root/docker-compose.yml
    - name: change permissions .log
      shell: chown -R 1000:1000 /jenkins-data/
    - name: Deploy containers
      shell: docker-compose up -d 
