version: '3'
services: 
  jenkins: 
    image: jenkins/jenkins
    container_name: 'jenkins'
    hostname: jenkins.ajcproject.com
    restart: always
    environment: 
      - TZ=Europe/Paris
    volumes: 
      - "/jenkins-data:/var/jenkins_home"
    ports: 
      - 8080:8080
      - 50000:50000
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    hostname: gitlab
    ports:
      - '8081:80'
    environment:
      TZ: Europe/Paris
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Europe/Paris'
        gitlab_rails['gitlab_email_from'] = 'nm.rumianteva@yahoo.fr'
        gitlab_rails['manage_backup_path'] = true
        gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"
        gitlab_rails['backup_archive_permissions'] = 0640
        gitlab_rails['backup_keep_time'] = 604800
        gitlab_rails['smtp_enable'] = true
        external_url 'http://104.210.89.208/'
    volumes:
      - '/gitlab/etc:/etc/gitlab'
      - '/gitlab/logs:/var/log/gitlab'
      - '/gitlab/data/:/var/opt/gitlab'
 
  db: 
    image: mariadb:10.2
    volumes: 
      - ${PWD}/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: administrateur
      MYSQL_DATABASE: dbtest
      MYSQL_USER: administrateur
      MYSQL_PASSWORD: administrateur
