version: '3'
services: 
  jenkins: 
    image: jenkins/jenkins
    container_name: 'jenkins'
    hostname: jenkins.ajcproject.com
    environment: 
      - TZ=Europe/Paris
    volumes: 
      - "/jenkins-data:/var/jenkins_home"
    ports: 
      - 8080:8080
      - 50000:50000

