version: '3'
services: 
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8082:80
    links:
      - db
    volumes:
      - /var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php

  db: 
    image: mariadb:10.2
    volumes: 
      - ${PWD}/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: administrateur
      MYSQL_DATABASE: dbtest
      MYSQL_USER: administrateur
      MYSQL_PASSWORD: administrateur
  
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - /jekyll-data:/srv/jekyll
