version: '3'
services: 
  db: 
    image: mariadb:10.2
    volumes: 
      - ${PWD}/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: administrateur
      MYSQL_DATABASE: dbtest
      MYSQL_USER: administrateur
      MYSQL_PASSWORD: administrateur

